services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: albert
      MYSQL_PASSWORD: albert
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root 
      PMA_PASSWORD: root
    ports:
      - "8080:80"
  
  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: db 
      WORDPRESS_DB_USER: albert
      WORDPRESS_DB_PASSWORD: albert
      WORDPRESS_DB_NAME: mydatabase 
    ports:
      - "8081:80"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db

volumes:
  db_data:
  wordpress:
