---
- hosts: all
  tasks:
  block:
    - name: Attempt task
      command: ls -la /root/var/www
  rescue:
    - name: This will run if the block has faile
      command: ls -la
  allways:
    - name: This will allways run
      debug: msg="This allways executes"
