services:
  ubuntu:
    build:
      context: .
      dockerfile: ubuntu/Dockerfile
    container_name: ubuntu_container1
    ports:
      - "2222:22"   # Forward port 2222 on host to 22 in container
    restart: unless-stopped
  alpine:
    build:
      context: .
      dockerfile: alpine/Dockerfile
    container_name: labalpine1
    ports:
      - "2223:22"   # Forward port 2222 on host to 22 in container
    restart: unless-stopped
  redhat:
    build:
      context: .
      dockerfile: redhat/Dockerfile
    container_name: labredhat1
    ports:
      - "2224:22"   # Forward port 2222 on host to 22 in container
    restart: unless-stopped
  debian:
    build:
      context: .
      dockerfile: debian/Dockerfile
    container_name: LabDebian1
    ports:
      - "2225:22"   # Forward port 2222 on host to 22 in container
    restart: unless-stopped
  archlinux:
    build:
      context: .
      dockerfile: archlinux/Dockerfile
    container_name: LabArchlinux1
    ports:
      - "2226:22"   # Forward port 2222 on host to 22 in container
    restart: unless-stopped

