# Dockefile for task5
# Arg is a variable which can be used in dockerfiles it is used when doing docker build command
ARG UBUNTU_VERSION
FROM ubuntu:${UBUNTU_VERSION}
CMD [ "echo", "Hello world" ]

# For example you can do docker build --build-arg UBUNTU_VERSION=rolling--tag "ubunturolling" .

