name: Terraform Chekov with apply on specific workspace(instance_types)

on:
  workflow_dispatch: 
    inputs:
      environment:
        type: choice
        description: Environment
        options: 
        - dev
        - stage
        - prod
        default: test
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
        id-token: write
        contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::615299760116:role/github-actions-admin-role
          aws-region: eu-central-1

      - name: Verify AWS Access
        run: aws sts get-caller-identity

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: 48_terraform_checkov
          framework: terraform
          soft_fail: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: |
          cd 48_terraform_checkov
          terraform fmt -check

      - name: Terraform Plan
        run: |
          cd 48_terraform_checkov
          terraform init
          terraform plan -var-file=vars.${{ github.event.inputs.environment}}.tfvars
      
      - name: Terraform apply
        run: |
          cd 48_terraform_checkov
          terraform apply -auto-approve "${{ github.event.inputs.environment }}"