name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Login to docker
      run: docker login -u albertasm -p ${{ secrets.DOCKER_PASS}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag albertasm/testimage:latest
    - name: Push image
      run: docker push albertasm/testimage:latest
