name: Terraform plan while selecting environment and apply those changes

on:
    workflow_dispatch:
        inputs:
            environment:
                type: choice
                description: Environment
                options:
                - dev
                - stage
                - prod
                default: default

jobs:
    build:
        env: 
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_PASSWORD }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
        
        - name: Login to azure
          run: |
            az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        

        - name: Terraform Format
          run: terraform fmt -check


        - name: Terraform Plan
          run: |
            cd 27-terraform-workspace
            terraform init
            terraform workspace select ${{ github.event.inputs.environment }}
            terraform plan -var-file vars.${{ github.event.inputs.environment }}.tfvars -out ${{ github.event.inputs.environment }}.plan

        - name: Terraform apply
          run: |
            cd 27-terraform-workspace
            terraform workspace select ${{ github.event.inputs.environment }}
            terraform apply -auto-approve "${{ github.event.inputs.environment }}.plan"
            