name: Terraform serverless aws

on:
    workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./47_terraform_lambda
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                role-to-assume: arn:aws:iam::615299760116:role/github-actions-admin-role
                aws-region: eu-central-1
            
            - name: Terraform format
              run: terraform fmt -check

            - name: Terraform apply auto approve
              run: terraform appy --auto-approve
            